### PR TITLE
Signup fix

### LINKED ISSUE #55: Fix App User Signup page
Currently the app redirects to an API endpoint. Instead we want the app to send an asynchronous AJAX request to the proper endpoint and based on the response save a new JWT in a cookie and redirect, or show an error message.

### PR DESCRIPTION
**Pull request by Willgar**
It now handles redirections correctly and supplies the client with a JWT for the newly created user. 
Closes #55

### CODE REVIEW

File: recruitment-api/controller/UserController.ts [hunk 1]
```diff
@@ -26,9 +27,17 @@ export default class UserController extends IController {
 
   async post({ request, response }: Context) {
     this.log.debug("Request to: POST /user");
-    const user = await bodyMappingFormData(request, User);
+    response.headers.append("Access-Control-Allow-Origin", "*");  
+    const user = await bodyMappingForm(request, User);
     if (await UserController.userService.saveUser(user)) {
-      created(response, `User ${user.firstName} was successfully created!`);
+      const strippedUser = {
```
Comment (Luddeeeeeee) [inline recruitment-api/controller/UserController.ts:33]: Do we really want to return a jwt directly
This means the user does not need to login after they have created an account
We would probably like to simulate the imagined confirmation email and then you can login

**Review by Luddeeeeeee — CHANGES_REQUESTED** [review]

File: recruitment-api/controller/UserController.ts (hunk 1 above)
Comment (Willgar) [reply recruitment-api/controller/UserController.ts:33]: If we had the option to send out confirmation mails that would be a reasonable idea, and personally I find it wacky to have to login again straight after creating an account.

Comment (Willgar) [reply recruitment-api/controller/UserController.ts:33]: #55 also mentions wanting to return a JWT.

Comment (WilliamRagstad) [reply recruitment-api/controller/UserController.ts:33]: And because we now have `strippedUser` in both the `post` and `validation` endpoints, it might be good to extract that functionality to a separate function or even model, `StrippedUser`/`SafeUser`.

Comment (Luddeeeeeee) [reply recruitment-api/controller/UserController.ts:33]: true, true

**Review by Luddeeeeeee — APPROVED** [review]

File: recruitment-api/controller/UserController.ts (hunk 1 above)
Comment (WilliamRagstad) [reply recruitment-api/controller/UserController.ts:33]: And it would be good if we added a new column to the database for indicating if a user has verified their email after signing up. In that case, the `validation` endpoint needs to be updated as well.

File: recruitment-app/lib/api.ts [hunk 2]
```diff
@@ -19,11 +19,12 @@ const firstOf = <T>(ps: Promise<T>[]): Promise<T> | Promise<string[]> =>
 /**
  * Fetch data from the local or public API.
  * @param endpoint Name of the endpoint without the base url. Must not contain a leading slash!
+ * @param options Optional settings that you want to apply to the request. 
+ * @returns The response from the server. 
  */
-export async function getAPI(endpoint: string) {
-
+export async function getAPI(endpoint: string, options: any = []) {
```
Comment (WilliamRagstad) [inline recruitment-app/lib/api.ts:25]: Use same type for `options` as `init` for `fetch`:
```ts
function fetch(input: string | Request | URL, init?: (RequestInit & {
    client: Deno.HttpClient;
}) | undefined): Promise<Response>
```
Default to `undefined` not `[]`.

File: recruitment-app/pages/signup.tsx [hunk 3]
```diff
@@ -1,34 +1,55 @@
...
+    event.preventDefault();
+    setError("");
     const passwordElm = document.getElementById("password") as HTMLInputElement;
     const password = passwordElm.value;
     const hashedPassword = hashPassword(password);
     passwordElm.value = hashedPassword;
+    const data = new URLSearchParams();
+    for (const pair of new FormData(document.getElementById('signup_form_data') as HTMLFormElement | undefined)){
+      data.append(pair[0], pair[1] as string);
+    }
```
Comment (WilliamRagstad) [inline recruitment-app/pages/signup.tsx:29]: You can use this instead:
```ts
const data = new URLSearchParams(new FormData(formElement));
```
From: https://stackoverflow.com/questions/46640024/how-do-i-post-form-data-with-fetch-api

File: recruitment-app/pages/signup.tsx [hunk 4]
```diff
@@ -1,34 +1,55 @@
...
+    const res = await getAPI('user', {
+      method: 'POST',
+      body: data,
+    });
+    const jwt = await res.text();
+    if(jwt && res.status==201){
```
Comment (WilliamRagstad) [inline recruitment-app/pages/signup.tsx:35]: Use `res.ok && jwt` instead.

File: recruitment-app/pages/signup.tsx [hunk 5]
```diff
@@ -1,34 +1,55 @@
...
   return (
     <DefaultPage header="Sign up" user={user}>
       {(!user && (
         <form
-          action="http://localhost:8000/user"
-          method="post"
           className="signup_form"
           encType="multipart/form-data"
           onSubmit={submitForm}
+          id="signup_form_data"
```
Comment (WilliamRagstad) [inline recruitment-app/pages/signup.tsx:52]: It's not form data, it's just a form. Maybe rename to `signup_form`?

**Review by WilliamRagstad — CHANGES_REQUESTED** [review]

File: recruitment-api/controller/UserController.ts (hunk 1 above)
Comment (Willgar) [reply recruitment-api/controller/UserController.ts]: There is now a new SafeUser DTO instead of strippedUser.

**Review by Luddeeeeeee — APPROVED** [review]
